### ISSUE TITLE
发布完招聘信息，不能修改，提示js错误

### ISSUE THREAD

**Issue by justjavac** [xinyu198736/htmljs#18]
`<select>` 下面没有加载 `<option>`

![image](https://cloud.githubusercontent.com/assets/359395/8866754/9d6a3ba2-31f2-11e5-860d-88f21220452b.png)

**Comment by justjavac** [comment]
![image](https://cloud.githubusercontent.com/assets/359395/8866762/b7a9af20-31f2-11e5-9444-7bc7727eb881.png)

**Comment by xinyu198736** [comment]
哎呦
